backend:
  name: git-gateway
  repo: wtnabe/jekyll-and-netlify-test
media_folder: assets/img
publish_mode: editorial_workflow
collections:
  - 
    label: pages
    name: pages
    create: true
    folder: source
    extension: md
    fields:
      - 
        label: タイトル
        name: title
        widget: string
      -
        label: カテゴリ
        name: category
        widget: select
        options:
          - food
          - shopping
          - play
          - work
      -
        label: 更新日
        name: date
        widget: date
      -
        label: 本文
        name: body
        widget: markdown
  - 
    label: rawpages
    name: rawpages
    create: true
    folder: source
    extension: html
    fields:
      - 
        label: タイトル
        name: title
        widget: string
      -
        label: 更新日
        name: date
        widget: date
      -
        label: 本文
        name: body
        widget: text
  - 
    label: filesデータ
    name: files data
    files: 
      - 
        label: カテゴリ
        name: category
        file: source/_data/category.yml
        widget: list
        allow_add: true
        fields:
          - 
            label: カテゴリ
            name: category
            field: 
              - 
                label: 日本語
                name: japanese
                widget: string
              - 
                  label: name
                  name: name
                  widget: string
  -
    label: folderデータ
    name: folder data
    folder: source
    extension: yaml
    fields:
      -
        label: key
        name: key
        widget: string
      -
        label: foo
        name: foo
        widget: string
