include:
  - admin/*
exclude: 
  - 'data-*.yaml'
defaults:
  - 
    scope:
      path: 'index.html'
    values:
      layout: top
  - 
    scope:
      path: 'products.md'
    values:
      layout: default
  - 
    scope:
      path: 'products-*.md'
    values:
      layout: default
plugins:
  - jekyll-assets
